### PR TITLE
Moveing files from pdf to md - WIP

### PR DESCRIPTION
**Pull request by laurafitzgerald**
WIP 

- [x] buddy.pdf
- [x] general-rules.pdf

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@JameelB I was looking for the instructions to build the site from the content repo. Do you know where they are?

**Comment by laurafitzgerald** [comment]
@judyobrienie I see that you merged some prs there, do you know the process for building the site from the content repo?

**Comment by judyobrienie** [comment]
@laurafitzgerald When I merged the changes the site was automatically updated 
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Review by JameelB — DISMISSED** [review]

**Comment by laurafitzgerald** [comment]
Hi @JameelB changes pushed now. 
Verification steps are:
Run `tutors` command from root directory.
Navigate to public-site/index.html
Click through `your first day` and `buddy guide`. 
The buddy guide should work as book form rather than pdf.

**Comment by laurafitzgerald** [comment]
@JameelB also did the same for general rules. would you mind also verifying that using the same steps.

**Review by JameelB — APPROVED** [review]
Changes looks good and verified.
- [x] Public site is generated.
- [x] Buddy guide renders correctly as expected.
- [x] General rules renders correctly as expected.

**Comment by laurafitzgerald** [comment]
@JameelB thanks for the review. Merging

**Pull request merged**
